image: node:12.18.3-buster-slim
before_script:
  - apt-get update && apt-get install -y python-yaml git

build:
  script:
    - bash build.sh

pages:
  stage: deploy
  script:
    - mv site/public ./
  artifacts:
    paths:
    - public
  only:
    - master