image: registry.gitlab.com/ecal/ecaldpgplots

build:
  stage: build
  script:
    - bash build.sh
  artifacts:
    paths:
      - site/public
  cache:
    paths:
      - site/public


pages:
  stage: deploy
  script:
    - mv site/public ./
  artifacts:
    paths:
    - public
  only:
    - master