image: node:12.18.3-buster-slim

pages:
  script:
  - cd site; npm ci; node_modules/.bin/ng build --prod --base-href https://ecal.gitlab.io/ecaldpgplots/ --deploy-url https://ecal.gitlab.io/ecaldpgplots/; cd ..; pwd
  artifacts:
    paths:
    - public
  only:
    - master