image: gitlab-registry.cern.ch/ecalpfg/ecaldpgplots

lint:
  stage: build
  interruptible: true
  before_script:
    - python3 validate_content.py content
    - cd site
    - npm ci
    - cd -
  cache:
    paths:
      - site/node_modules
  script:
    - cd site
    - npm run lint
    - cd -

build:
  stage: test
  interruptible: true
  script:
    - bash build.sh
  artifacts:
    paths:
      - site/public
  cache:
    paths:
      - site/public


pages:
  stage: deploy
  script:
    - gzip -r -k -9 site/public/*.js site/public/*.css
    - mv site/public ./
  artifacts:
    paths:
    - public
  only:
    - master