image: node:12.18.3-buster-slim

pages:
  script:
  - npm install
  - cd site; npm install; ../node_modules/.bin/ng build --prod --base-href https://thegriglat.gitlab.io/ecaldpgplots/ --deploy-url https://thegriglat.gitlab.io/ecaldpgplots/; cd ..; pwd
  - mkdir public; mv site/dist/site/* public/
  artifacts:
    paths:
    - public
  only:
    - master