image: registry.gitlab.com/ecal/ecaldpgplots



lint:
  stage: build
  interruptible: true
  before_script:
    - cd site
    - npm ci
    - cd -
  cache:
    paths:
      - site/node_modules
  script:
    - cd site
    - npm run lint
    - cd -

build:
  stage: test
  interruptible: true
  script:
    - bash build.sh
  artifacts:
    paths:
      - site/public
  cache:
    paths:
      - site/public


pages:
  stage: deploy
  script:
    - mv site/public ./
  artifacts:
    paths:
    - public
  only:
    - master