image: gitlab-registry.cern.ch/ecalpfg/ecaldpgplots

build:
  stage: build
  interruptible: true
  before_script:
    - cd site
    - npm ci
    - npm run lint
    - cd -
  script:
    - make -j $(grep -c proc /proc/cpuinfo)
    - gzip -r -k -9 site/public/*.js site/public/*.css site/public/assets/*.json
    - echo "${EOS_ACCOUNT_PASSWORD}" | kinit ${EOS_ACCOUNT_USERNAME}@CERN.CH
    - rsync -avz --delete site/public/ EOS_ACCOUNT_USERNAME@lxplus.cern.ch:/eos/user/g/grlatysh/www/
  only:
    - master