FROM node:12.18.3-buster-slim

RUN apt-get update && apt-get install -y python-yaml python3 python3-yaml git git-lfs \
 && apt-get clean autoclean && apt-get autoremove --yes && rm -rf /var/lib/{apt,dpkg,cache,log}